#!/usr/bin/env node
// Exports a testplan.json to standard Playwright specs so the suite can run in
// CI without Claude. One spec file per case plus a minimal playwright.config.
//
// Usage: node export-specs.mjs --plan e2e/testplan.json --out e2e/specs

import fs from 'node:fs';
import path from 'node:path';

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--plan') args.plan = argv[++i];
    else if (argv[i] === '--out') args.out = argv[++i];
  }
  if (!args.plan || !args.out) {
    console.error('e2e-evidence: usage: export-specs.mjs --plan <testplan.json> --out <dir>');
    process.exit(2);
  }
  return args;
}

const args = parseArgs(process.argv.slice(2));
const plan = JSON.parse(fs.readFileSync(args.plan, 'utf8'));
fs.mkdirSync(args.out, { recursive: true });

const q = (s) => JSON.stringify(String(s));
const reEscape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// '{{ENV:X}}' -> env('X'); 'a{{ENV:X}}b' -> `a${env('X')}b`; plain -> "literal"
function valueExpr(value, usesEnv) {
  const str = String(value);
  const re = /\{\{ENV:([A-Za-z0-9_]+)\}\}/g;
  if (!re.test(str)) return q(str);
  usesEnv.flag = true;
  re.lastIndex = 0;
  const whole = str.match(/^\{\{ENV:([A-Za-z0-9_]+)\}\}$/);
  if (whole) return `env(${q(whole[1])})`;
  const tpl = str
    .replace(/[`\\]/g, '\\$&')
    .replace(re, (_, name) => `\${env(${q(name)})}`);
  return `\`${tpl}\``;
}

function resolveUrl(u, baseUrl) {
  if (/^https?:\/\//i.test(u)) return u;
  return new URL(u, baseUrl).toString();
}

function stepCode(step, baseUrl, usesEnv) {
  const loc = step.selector ? `page.locator(${q(step.selector)}).first()` : null;
  switch (step.action) {
    case 'navigate': return [`await page.goto(${q(resolveUrl(step.url, baseUrl))});`];
    case 'fill': return [`await ${loc}.fill(${valueExpr(step.value, usesEnv)});`];
    case 'select': return [`await ${loc}.selectOption(${valueExpr(step.value, usesEnv)});`];
    case 'click': return [`await ${loc}.click();`];
    case 'press': return [step.selector ? `await ${loc}.press(${q(step.value)});` : `await page.keyboard.press(${q(step.value)});`];
    case 'wait': return [step.selector ? `await ${loc}.waitFor({ state: 'visible' });` : `await page.waitForTimeout(${Number(step.ms ?? 1000)});`];
    case 'assert': {
      const kind = step.kind ?? 'visible';
      if (kind === 'visible') return [`await expect(${loc}).toBeVisible();`];
      if (kind === 'text') return [`await expect(${loc}).toContainText(${valueExpr(step.value, usesEnv)});`];
      if (kind === 'url') return [`await expect(page).toHaveURL(new RegExp(${q(reEscape(String(step.value)))}));`];
      if (kind === 'count') return [`await expect(page.locator(${q(step.selector)})).toHaveCount(${Number(step.value)});`];
      throw new Error(`Unknown assert kind '${kind}' in ${step.n}`);
    }
    default: throw new Error(`Unknown action '${step.action}' in step ${step.n}`);
  }
}

const files = [];
for (const tc of plan.cases ?? []) {
  const usesEnv = { flag: false };
  const body = [];
  for (const step of tc.steps) {
    body.push(`  // Step ${step.n}`);
    for (const line of stepCode(step, plan.baseUrl, usesEnv)) body.push(`  ${line}`);
  }
  const envHelper = usesEnv.flag
    ? `\nconst env = (name) => {\n  const v = process.env[name];\n  if (v === undefined) throw new Error(\`Missing environment variable \${name}\`);\n  return v;\n};\n`
    : '';
  const src = `// Generated by e2e-evidence from ${path.basename(args.plan)} — edit the plan, not this file.
import { test, expect } from '@playwright/test';
${envHelper}
test(${q(`${tc.id} · ${tc.title}`)}, async ({ page }) => {
${body.join('\n')}
});
`;
  const slug = tc.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48);
  const file = path.join(args.out, `${tc.id.toLowerCase()}-${slug}.spec.mjs`);
  fs.writeFileSync(file, src);
  files.push(file);
}

const configPath = path.join(args.out, 'playwright.config.mjs');
fs.writeFileSync(configPath, `// Generated by e2e-evidence.
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: '.',
  timeout: 30000,
  retries: 0,
  reporter: [['list'], ['html', { open: 'never', outputFolder: 'playwright-report' }]],
  use: {
    viewport: { width: 1280, height: 800 },
    video: 'on',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },
});
`);

console.log(`${files.length} spec(s) exported to ${args.out}`);
for (const f of files) console.log(`  ${f}`);
console.log(`CONFIG=${configPath}`);
